CREATE TABLE IF NOT EXISTS Client (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	role INTEGER DEFAULT 0 NOT NULL,
	phone TEXT NOT NULL,
	hash_password TEXT NOT NULL,
    	surname TEXT NOT NULL,
    	name TEXT NOT NULL,
	patronymic TEXT,
    	address TEXT DEFAULT 'Не указан' NOT NULL,
    	discount INTEGER DEFAULT 0 NOT NULL,
	amount_of_purchased_tickets INTEGER DEFAULT 0 NOT NULL
);


CREATE TABLE IF NOT EXISTS Employee (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	role INTEGER DEFAULT 1 NOT NULL,
	phone TEXT NOT NULL,
	hash_password TEXT NOT NULL,
	surname TEXT NOT NULL,
	name TEXT NOT NULL,
	patronymic TEXT
);


CREATE TABLE IF NOT EXISTS City (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	title TEXT NOT NULL,
	climate TEXT NOT NULL,
	activity_flag INTEGER DEFAULT 1 NOT NULL
);


CREATE TABLE IF NOT EXISTS Hotel (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	id_city INTEGER NOT NULL,
	title TEXT NOT NULL,
	category INTEGER NOT NULL,
	address TEXT NOT NULL,
	activity_flag INTEGER DEFAULT 1 NOT NULL,
	FOREIGN KEY (id_city) REFERENCES City (id)
);


CREATE TABLE IF NOT EXISTS Ticket (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	price INTEGER NOT NULL,
	quantity INTEGER NOT NULL,
	id_hotel INTEGER NOT NULL,
	id_departure_city INTEGER NOT NULL,
	duration INTEGER NOT NULL,
	travel_time INTEGER NOT NULL,
	departure_date TEXT NOT NULL,
	activity_flag INTEGER DEFAULT 1 NOT NULL,
	FOREIGN KEY (id_hotel) REFERENCES id (Hotel),
	FOREIGN KEY (id_departure_city) REFERENCES City (id)
);


CREATE TABLE IF NOT EXISTS Client_tickets (
	id_client INTEGER NOT NULL,
	id_ticket INTEGER NOT NULL,
	quantity INTEGER NOT NULL,
	FOREIGN KEY (id_client) REFERENCES Client (id),
	FOREIGN KEY (id_ticket) REFERENCES Ticket (id)
);

